defaults: &defaults
  max_rows: 15
  max_columns: 6
  date_time_format: '%e %B %Y at %H:%M'
  sort_books_by: 'title ASC'

development:
  <<: *defaults
  application_name: 'Bicherwuerm [dev]'

test:
  <<: *defaults
  application_name: 'Bicherwuerm [test]'

production:
  <<: *defaults
  application_name: 'Bicherwuerm'
